import type { Game, MonetizationImpact } from "./types";
import { CURATED_APPIDS } from "./steamInference";

export const mockGameLibrary: Game[] = [
  {
    id: "stardew-valley",
    title: "Stardew Valley",
    platform: "Steam",
    genre: ["Simulation", "RPG"],
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseYear: 2016,
    hoursPlayed: 248,
    lastPlayed: "2025-06-28",
    price: 14.99,
    coverColor: "bg-green-400",
    ageRating: "E10+",
    requiresOnline: false,
    estimatedHoursToComplete: 50,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 97,
  },
  {
    id: "hollow-knight",
    title: "Hollow Knight",
    platform: "Steam",
    genre: ["Action", "Platformer"],
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseYear: 2017,
    hoursPlayed: 42,
    lastPlayed: "2025-06-15",
    price: 14.99,
    coverColor: "bg-indigo-400",
    ageRating: "E10+",
    requiresOnline: false,
    estimatedHoursToComplete: 40,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 95,
  },
  {
    id: "hades",
    title: "Hades",
    platform: "Steam",
    genre: ["Roguelike", "Action"],
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseYear: 2020,
    hoursPlayed: 76,
    lastPlayed: "2025-06-01",
    price: 24.99,
    coverColor: "bg-purple-600",
    ageRating: "T",
    requiresOnline: false,
    estimatedHoursToComplete: 25,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 98,
  },
  {
    id: "elden-ring",
    title: "Elden Ring",
    platform: "Steam",
    genre: ["Action RPG"],
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseYear: 2022,
    hoursPlayed: 187,
    lastPlayed: "2025-05-20",
    price: 59.99,
    coverColor: "bg-amber-500",
    ageRating: "M",
    requiresOnline: false,
    estimatedHoursToComplete: 60,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 1,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 96,
  },
  {
    id: "rocket-league",
    title: "Rocket League",
    platform: "Epic",
    genre: ["Sports", "Action"],
    developer: "Psyonix",
    publisher: "Epic Games",
    releaseYear: 2015,
    hoursPlayed: 203,
    lastPlayed: "2025-06-25",
    price: 0,
    coverColor: "bg-sky-500",
    ageRating: "E",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 82,
  },
  {
    id: "fortnite",
    title: "Fortnite",
    platform: "Epic",
    genre: ["Battle Royale", "Action"],
    developer: "Epic Games",
    publisher: "Epic Games",
    releaseYear: 2017,
    hoursPlayed: 312,
    lastPlayed: "2025-06-29",
    price: 0,
    coverColor: "bg-blue-500",
    ageRating: "T",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: true,
      hasAds: false,
    },
    communityScore: 74,
  },
  {
    id: "apex-legends",
    title: "Apex Legends",
    platform: "Steam",
    genre: ["Battle Royale", "Action"],
    developer: "Respawn Entertainment",
    publisher: "EA",
    releaseYear: 2019,
    hoursPlayed: 156,
    lastPlayed: "2025-06-22",
    price: 0,
    coverColor: "bg-red-500",
    ageRating: "T",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: true,
      hasAds: false,
    },
    communityScore: 71,
  },
  {
    id: "genshin-impact",
    title: "Genshin Impact",
    platform: "Epic",
    genre: ["Action RPG", "Gacha"],
    developer: "HoYoverse",
    publisher: "HoYoverse",
    releaseYear: 2020,
    hoursPlayed: 421,
    lastPlayed: "2025-06-30",
    price: 0,
    coverColor: "bg-teal-500",
    ageRating: "T",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: true,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: true,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 76,
  },
  {
    id: "ea-fc-25",
    title: "EA FC 25",
    platform: "Steam",
    genre: ["Sports"],
    developer: "EA Sports",
    publisher: "EA",
    releaseYear: 2024,
    hoursPlayed: 89,
    lastPlayed: "2025-06-10",
    price: 69.99,
    coverColor: "bg-orange-500",
    ageRating: "E",
    requiresOnline: false,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: false,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: true,
      hasGacha: true,
      hasSocialPressure: true,
      hasAds: false,
    },
    communityScore: 45,
  },
  {
    id: "diablo-immortal",
    title: "Diablo Immortal",
    platform: "Epic",
    genre: ["Action RPG"],
    developer: "Blizzard",
    publisher: "Blizzard",
    releaseYear: 2022,
    hoursPlayed: 34,
    lastPlayed: "2025-04-12",
    price: 0,
    coverColor: "bg-red-900",
    ageRating: "M",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: true,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: true,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: true,
      hasGacha: true,
      hasSocialPressure: true,
      hasAds: false,
    },
    communityScore: 32,
  },
  // Phase 2 additions
  {
    id: "among-us",
    title: "Among Us",
    platform: "Steam",
    genre: ["Social Deduction", "Party"],
    developer: "Innersloth",
    publisher: "Innersloth",
    releaseYear: 2018,
    hoursPlayed: 28,
    lastPlayed: "2025-05-10",
    price: 5.0,
    coverColor: "bg-rose-400",
    ageRating: "E10+",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 88,
  },
  {
    id: "valorant",
    title: "Valorant",
    platform: "Epic",
    genre: ["Tactical Shooter"],
    developer: "Riot Games",
    publisher: "Riot Games",
    releaseYear: 2020,
    hoursPlayed: 134,
    lastPlayed: "2025-06-27",
    price: 0,
    coverColor: "bg-rose-600",
    ageRating: "T",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: true,
      hasAds: false,
    },
    communityScore: 79,
  },
  {
    id: "league-of-legends",
    title: "League of Legends",
    platform: "Epic",
    genre: ["MOBA"],
    developer: "Riot Games",
    publisher: "Riot Games",
    releaseYear: 2009,
    hoursPlayed: 567,
    lastPlayed: "2025-06-30",
    price: 0,
    coverColor: "bg-blue-700",
    ageRating: "T",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: true,
      hasAds: false,
    },
    communityScore: 69,
  },
  {
    id: "pokemon-go",
    title: "Pokémon GO",
    platform: "Epic",
    genre: ["AR", "RPG"],
    developer: "Niantic",
    publisher: "Niantic",
    releaseYear: 2016,
    hoursPlayed: 189,
    lastPlayed: "2025-06-30",
    price: 0,
    coverColor: "bg-yellow-400",
    ageRating: "E",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: true,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: true,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 72,
  },
  {
    id: "candy-crush-saga",
    title: "Candy Crush Saga",
    platform: "Epic",
    genre: ["Puzzle", "Casual"],
    developer: "King",
    publisher: "Activision Blizzard",
    releaseYear: 2012,
    hoursPlayed: 41,
    lastPlayed: "2025-06-20",
    price: 0,
    coverColor: "bg-pink-400",
    ageRating: "E",
    requiresOnline: false,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: true,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: true,
      hasGacha: false,
      hasSocialPressure: true,
      hasAds: true,
    },
    communityScore: 58,
  },
  // GOG library
  {
    id: "witcher-3",
    title: "The Witcher 3: Wild Hunt",
    platform: "GOG",
    genre: ["Action RPG", "Open World"],
    developer: "CD Projekt Red",
    publisher: "CD Projekt Red",
    releaseYear: 2015,
    hoursPlayed: 143,
    lastPlayed: "2025-06-10",
    price: 39.99,
    coverColor: "bg-stone-500",
    ageRating: "M",
    requiresOnline: false,
    estimatedHoursToComplete: 100,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 2,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 96,
  },
  {
    id: "disco-elysium",
    title: "Disco Elysium",
    platform: "GOG",
    genre: ["RPG", "Detective"],
    developer: "ZA/UM",
    publisher: "ZA/UM",
    releaseYear: 2019,
    hoursPlayed: 62,
    lastPlayed: "2025-03-22",
    price: 39.99,
    coverColor: "bg-amber-700",
    ageRating: "M",
    requiresOnline: false,
    estimatedHoursToComplete: 30,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 93,
  },
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    platform: "GOG",
    genre: ["RPG", "Strategy"],
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseYear: 2023,
    hoursPlayed: 210,
    lastPlayed: "2025-06-28",
    price: 59.99,
    coverColor: "bg-emerald-700",
    ageRating: "M",
    requiresOnline: false,
    estimatedHoursToComplete: 100,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 98,
  },
  {
    id: "kotor",
    title: "Star Wars: KOTOR",
    platform: "GOG",
    genre: ["RPG", "Action"],
    developer: "BioWare",
    publisher: "Aspyr",
    releaseYear: 2003,
    hoursPlayed: 38,
    lastPlayed: "2025-01-15",
    price: 9.99,
    coverColor: "bg-yellow-600",
    ageRating: "T",
    requiresOnline: false,
    estimatedHoursToComplete: 30,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 94,
  },
  {
    id: "divinity-original-sin-2",
    title: "Divinity: Original Sin 2",
    platform: "GOG",
    genre: ["RPG", "Strategy"],
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseYear: 2017,
    hoursPlayed: 84,
    lastPlayed: "2025-04-05",
    price: 44.99,
    coverColor: "bg-red-700",
    ageRating: "M",
    requiresOnline: false,
    estimatedHoursToComplete: 100,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 1,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 95,
  },
  {
    id: "celeste",
    title: "Celeste",
    platform: "Steam",
    genre: ["Platformer", "Indie"],
    developer: "Maddy Makes Games",
    publisher: "Maddy Makes Games",
    releaseYear: 2018,
    hoursPlayed: 18,
    lastPlayed: "2025-05-30",
    price: 19.99,
    coverColor: "bg-pink-600",
    ageRating: "E10+",
    requiresOnline: false,
    estimatedHoursToComplete: 10,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 98,
  },
  {
    id: "fall-guys",
    title: "Fall Guys",
    platform: "Epic",
    genre: ["Battle Royale", "Party"],
    developer: "Mediatonic",
    publisher: "Epic Games",
    releaseYear: 2020,
    hoursPlayed: 47,
    lastPlayed: "2025-06-18",
    price: 0,
    coverColor: "bg-yellow-400",
    ageRating: "E",
    requiresOnline: true,
    estimatedHoursToComplete: 0,
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
      hasAds: false,
    },
    communityScore: 78,
  },
];

// What real-money purchases actually buy in each monetised demo game — the
// factual signal the risk engine uses to separate cosmetic spending from
// pay-for-power. Games not listed here have no monetisation (impact "none").
// Classifications are based on each game's live storefront at time of writing:
//   cosmetic    — skins/visuals only, zero gameplay advantage
//   convenience — time-savers, no competitive power
//   power       — purchases affect gameplay, progression, or competition
const MONETIZATION_IMPACT: Record<string, MonetizationImpact> = {
  "rocket-league": "cosmetic",
  fortnite: "cosmetic",
  "apex-legends": "cosmetic",
  "genshin-impact": "power",
  "ea-fc-25": "power",
  "diablo-immortal": "power",
  "among-us": "cosmetic",
  valorant: "cosmetic",
  "league-of-legends": "cosmetic",
  "pokemon-go": "convenience",
  "candy-crush-saga": "power",
  "fall-guys": "cosmetic",
};

for (const game of mockGameLibrary) {
  const impact = MONETIZATION_IMPACT[game.id];
  if (impact) game.mechanics.monetizationImpact = impact;
}

// Give curated games their Steam appid (reverse of CURATED_APPIDS) so the demo
// library shows real cover art too. Doesn't affect routing (ids are unchanged).
const APPID_BY_ID: Record<string, number> = {};
for (const [appid, id] of Object.entries(CURATED_APPIDS)) APPID_BY_ID[id] = Number(appid);
for (const game of mockGameLibrary) {
  if (!game.steamAppId && APPID_BY_ID[game.id]) game.steamAppId = APPID_BY_ID[game.id];
}
