import type { Game } from "./types";

export const mockGameLibrary: Game[] = [
  {
    id: "stardew-valley",
    title: "Stardew Valley",
    platform: "Steam",
    genre: ["Simulation", "RPG"],
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseYear: 2016,
    hoursPlayed: 248,
    lastPlayed: "2025-06-28",
    price: 14.99,
    coverColor: "bg-green-400",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
    },
    communityScore: 97,
  },
  {
    id: "hollow-knight",
    title: "Hollow Knight",
    platform: "Steam",
    genre: ["Action", "Platformer"],
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseYear: 2017,
    hoursPlayed: 42,
    lastPlayed: "2025-06-15",
    price: 14.99,
    coverColor: "bg-indigo-400",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
    },
    communityScore: 95,
  },
  {
    id: "hades",
    title: "Hades",
    platform: "Steam",
    genre: ["Roguelike", "Action"],
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseYear: 2020,
    hoursPlayed: 76,
    lastPlayed: "2025-06-01",
    price: 24.99,
    coverColor: "bg-purple-600",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
    },
    communityScore: 98,
  },
  {
    id: "elden-ring",
    title: "Elden Ring",
    platform: "Steam",
    genre: ["Action RPG"],
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    releaseYear: 2022,
    hoursPlayed: 187,
    lastPlayed: "2025-05-20",
    price: 59.99,
    coverColor: "bg-amber-500",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: false,
      hasSeasonPass: false,
      hasMicrotransactions: false,
      dlcCount: 1,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: false,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
    },
    communityScore: 96,
  },
  {
    id: "rocket-league",
    title: "Rocket League",
    platform: "Epic",
    genre: ["Sports", "Action"],
    developer: "Psyonix",
    publisher: "Epic Games",
    releaseYear: 2015,
    hoursPlayed: 203,
    lastPlayed: "2025-06-25",
    price: 0,
    coverColor: "bg-sky-500",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: false,
    },
    communityScore: 82,
  },
  {
    id: "fortnite",
    title: "Fortnite",
    platform: "Epic",
    genre: ["Battle Royale", "Action"],
    developer: "Epic Games",
    publisher: "Epic Games",
    releaseYear: 2017,
    hoursPlayed: 312,
    lastPlayed: "2025-06-29",
    price: 0,
    coverColor: "bg-blue-500",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: false,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: true,
    },
    communityScore: 74,
  },
  {
    id: "apex-legends",
    title: "Apex Legends",
    platform: "Steam",
    genre: ["Battle Royale", "Action"],
    developer: "Respawn Entertainment",
    publisher: "EA",
    releaseYear: 2019,
    hoursPlayed: 156,
    lastPlayed: "2025-06-22",
    price: 0,
    coverColor: "bg-red-500",
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: false,
      hasSocialPressure: true,
    },
    communityScore: 71,
  },
  {
    id: "genshin-impact",
    title: "Genshin Impact",
    platform: "Epic",
    genre: ["Action RPG", "Gacha"],
    developer: "HoYoverse",
    publisher: "HoYoverse",
    releaseYear: 2020,
    hoursPlayed: 421,
    lastPlayed: "2025-06-30",
    price: 0,
    coverColor: "bg-teal-500",
    mechanics: {
      hasLootBoxes: false,
      hasBattlePass: true,
      hasSeasonPass: false,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: true,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: false,
      hasGacha: true,
      hasSocialPressure: false,
    },
    communityScore: 76,
  },
  {
    id: "ea-fc-25",
    title: "EA FC 25",
    platform: "Steam",
    genre: ["Sports"],
    developer: "EA Sports",
    publisher: "EA",
    releaseYear: 2024,
    hoursPlayed: 89,
    lastPlayed: "2025-06-10",
    price: 69.99,
    coverColor: "bg-orange-500",
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: false,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: false,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: true,
      hasGacha: true,
      hasSocialPressure: true,
    },
    communityScore: 45,
  },
  {
    id: "diablo-immortal",
    title: "Diablo Immortal",
    platform: "Epic",
    genre: ["Action RPG"],
    developer: "Blizzard",
    publisher: "Blizzard",
    releaseYear: 2022,
    hoursPlayed: 34,
    lastPlayed: "2025-04-12",
    price: 0,
    coverColor: "bg-red-900",
    mechanics: {
      hasLootBoxes: true,
      hasBattlePass: true,
      hasSeasonPass: true,
      hasMicrotransactions: true,
      dlcCount: 0,
      hasEnergySystem: true,
      hasDailyLoginBonus: true,
      hasLimitedTimeEvents: true,
      hasPayToWin: true,
      hasGacha: true,
      hasSocialPressure: true,
    },
    communityScore: 32,
  },
];
